/*
 * generated by Xtext 2.33.0
 */
package xray


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XRayDSLRuntimeModule extends AbstractXRayDSLRuntimeModule {
}
