/*
 * generated by Xtext 2.33.0
 */
package xray.validation

import org.eclipse.xtext.validation.Check
import xray.xRayDSL.Mode
import xray.xRayDSL.Projection
import xray.xRayDSL.SixPedals
import xray.xRayDSL.ThreePedals
import xray.xRayDSL.System
import xray.xRayDSL.Behaviour

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class XRayDSLValidator extends AbstractXRayDSLValidator {

	@Check
	def checkThreeOrSixPedals(System system) {
	    if (system.configuration instanceof ThreePedals){
	        switch (system.configuration.pedal1.projection){
	            case Projection::ProjLateral: {error("Only Frontal Allowed",null)}
   	            case Projection::ProjBiplane: {error("Only Frontal Allowed",null)}
	            default: {
	            }
	        }
	        switch (system.configuration.pedal2.projection){
	            case Projection::ProjLateral: {error("Only Frontal Allowed",null)}
   	            case Projection::ProjBiplane: {error("Only Frontal Allowed",null)}
	            default: {
	            }
	        }
	        switch (system.configuration.pedal3.projection){
	            case Projection::ProjLateral: {error("Only Frontal Allowed",null)}
   	            case Projection::ProjBiplane: {error("Only Frontal Allowed",null)}
	            default: {
	            }
	        }
	        switch (system.configuration.pedal1.mode){
	            case Mode::ModeImage: {error("Only Video Allowed",null)}
	            default: {
	            }
	        }
	        switch (system.configuration.pedal2.mode){
	            case Mode::ModeImage: {error("Only Video Allowed",null)}
	            default: {
	            }
	        }
	        switch (system.configuration.pedal3.mode){
	            case Mode::ModeImage: {error("Only Video Allowed",null)}
	            default: {
	            }
	        }
	    }
	    if (system.configuration instanceof SixPedals){
	        switch (system.logic.differentdosebehaviour.behaviour){
	            case Behaviour::EarlyOverride: {error("Only HighOverride or LowOverride Allowed",null)}
	            default: {
	            }
	        }
	    }	    
	}
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					XRayDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
