@startuml component

' Create three components for Pedal
package "Pedal Board" {
component [Low-Dose X-Ray] as comp_pedal_low
component [High-Dose X-Ray] as comp_pedal_high
component [Unknown Pedal] as comp_pedal_unknown
}

interface "Pedal \nStep" as intf_pedal_step
component [Pedal Mapper] as comp_pedal_mapper
interface "X-Ray \nRequests" as intf_xray_req
component [Action Logic] as comp_act_log
interface "X-Ray \nCommands" as intf_xray_commands
component [X-Ray Controller] as comp_xray_control
interface "X-Ray \nImages" as intf_xray_img
component [Image Processor] as comp_image_proc
interface "Readable \nVisual Images" as intf_visual_images
component [Screen] as comp_screen
interface "Configuration \nSettings" as intf_config_set
component [System Configurator] as comp_sys_config
interface "Selected \nConfiguration \nand Procedure" as intf_sys_config_med_proc
component [Tablet] as comp_tablet
interface "All \nConfiguration \nand Procedure" as intf_sys_config_comp_set
database "Procedure \nDatabase" as data_proc_data

' Create two components for Pedal
package "X-Ray Plane" {
component [X-Ray \nTube] as comp_xray_tube
component [X-Ray \nDetector] as comp_xray_detector
interface "X-Ray \nTransmitter" as intf_xray_transmit
interface "X-Ray \nReceiver" as intf_xray_receive
}
component [Table] as comp_table

interface "Activate/\nDeactivate \nCommand" as intf_act_deact_comm
interface "X-Ray \nData" as intf_act_xray_info


' Part 1 - Design from Pedal to Screen
    comp_pedal_low -up-- intf_pedal_step
    comp_pedal_high -up-- intf_pedal_step
    intf_pedal_step )-right- comp_pedal_mapper

    comp_pedal_mapper -right- intf_xray_req
    intf_xray_req )-right- comp_act_log

    comp_act_log -right- intf_xray_commands
    intf_xray_commands )-right- comp_xray_control

    comp_xray_control -right- intf_xray_img
    intf_xray_img )-right- comp_image_proc

    comp_image_proc -right- intf_visual_images
    intf_visual_images )-down-- comp_screen

' Part 2 - Design from Database to Image Processor
    data_proc_data -up-- intf_sys_config_comp_set
    intf_sys_config_comp_set )-right- comp_tablet

    comp_tablet -right- intf_sys_config_med_proc
    intf_sys_config_med_proc )-down-- comp_sys_config

    comp_sys_config -down- intf_config_set
    intf_config_set )-down- comp_xray_control
    intf_config_set )-down- comp_image_proc

' Part 3 - Design from X-Ray Plane to X-Ray Controller
    comp_xray_tube -down- intf_xray_transmit
    intf_xray_transmit )-down- comp_table

    comp_table -up- intf_xray_receive
    intf_xray_receive )-up- comp_xray_detector

    comp_xray_detector -up- intf_act_xray_info
    intf_act_xray_info )-up- comp_xray_control

    comp_xray_tube -up- intf_act_deact_comm
    comp_xray_detector -left- intf_act_deact_comm
    intf_act_deact_comm )-up- comp_xray_control


@enduml
