@startuml sequence-config

actor "Surgeon" as actor_surgeon
participant "Tablet" as participant_tablet
database "All Configuration \nand Procedure" as data_sys_config_comp_set

participant "System Configurator" as participant_sys_config
participant "X-Ray Controller" as participant_xray_control

participant "X-Ray Tube" as participant_xray_tube
participant "X-Ray Detector" as participant_xray_detector
participant "Image Processor" as participant_image_proc

' Design Part 1 - Start from Surgeon to Database
actor_surgeon -> participant_tablet: Access \nSettings Page
activate participant_tablet
participant_tablet -> data_sys_config_comp_set: Access All System Configurations \nand Component Settings
activate data_sys_config_comp_set
participant_tablet <-- data_sys_config_comp_set: Return All System Configurations \nand Component Settings
deactivate data_sys_config_comp_set
actor_surgeon <-- participant_tablet: Return \nSettings Page

' Design Part 2 - Start from Tablet
participant_tablet -\ participant_sys_config: Selected System Configurations \nand Medical Procedure

' Design Part 3 - System Configurator Onwards
activate participant_sys_config
participant_sys_config -\ participant_xray_control: Configuration \nCommands
activate participant_xray_control

participant_xray_control -\ participant_xray_tube: Activation/Deactivation Commands
activate participant_xray_tube
participant_xray_control -\ participant_xray_detector: Activation/Deactivation Commands
activate participant_xray_detector

participant_xray_control /- participant_xray_tube: Return State of Activation/Deactivation
deactivate participant_xray_tube
participant_xray_control /- participant_xray_detector: Return State of Activation/Deactivation
deactivate participant_xray_detector

participant_sys_config /- participant_xray_control: Return State of \nConfiguration
deactivate participant_xray_control

participant_sys_config -\ participant_image_proc: Configuration \nCommands
activate participant_image_proc
participant_sys_config /- participant_image_proc: Return State of \nConfiguration
deactivate participant_image_proc
' Design Part 3 - End of System Configurator

' Design Part 2 - End of Tablet
participant_tablet <- participant_sys_config: Return Selected System Configurations \nand Medical Procedure State
deactivate participant_sys_config

' Design Part 1 - End of Surgeon
actor_surgeon <-- participant_tablet: Return \nSettings State
deactivate participant_tablet

@enduml