/*
 * generated by Xtext 2.33.0
 */
package xray.ui.outline

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class XRayDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {

}
